"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from ... import substrait
import typing
import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class AsOfJoinRel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class AsOfJoinKeys(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ON_FIELD_NUMBER: builtins.int
        BY_FIELD_NUMBER: builtins.int

        @property
        def on(self) -> substrait.ibis.algebra_pb2.Expression:
            ...

        @property
        def by(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[substrait.ibis.algebra_pb2.Expression]:
            ...

        def __init__(self, *, on: typing.Optional[substrait.ibis.algebra_pb2.Expression]=..., by: typing.Optional[typing.Iterable[substrait.ibis.algebra_pb2.Expression]]=...) -> None:
            ...

        def HasField(self, field_name: typing_extensions.Literal['on', b'on']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing_extensions.Literal['by', b'by', 'on', b'on']) -> None:
            ...
    INPUT_KEYS_FIELD_NUMBER: builtins.int
    TOLERANCE_FIELD_NUMBER: builtins.int

    @property
    def input_keys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AsOfJoinRel.AsOfJoinKeys]:
        ...
    tolerance: builtins.int

    def __init__(self, *, input_keys: typing.Optional[typing.Iterable[global___AsOfJoinRel.AsOfJoinKeys]]=..., tolerance: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['input_keys', b'input_keys', 'tolerance', b'tolerance']) -> None:
        ...
global___AsOfJoinRel = AsOfJoinRel